// <auto-generated />
using System;
using AzzyBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AzzyBot.Data.Migrations
{
    [DbContext(typeof(AzzyDbContext))]
    partial class AzzyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastChecksEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AzuraCastId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdateCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ServerStatus")
                        .HasColumnType("boolean");

                    b.Property<int>("UpdateNotificationCounter")
                        .HasColumnType("integer");

                    b.Property<bool>("Updates")
                        .HasColumnType("boolean");

                    b.Property<bool>("UpdatesShowChangelog")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AzuraCastId")
                        .IsUnique();

                    b.ToTable("AzuraCastChecks");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GuildId")
                        .HasColumnType("integer");

                    b.Property<decimal>("InstanceAdminRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NotificationChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("OutagesChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("AzuraCast");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastStationChecksEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("FileChanges")
                        .HasColumnType("boolean");

                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("AzuraCastStationChecks");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastStationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AzuraCastId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FileUploadChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("FileUploadPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSkipTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PreferHls")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RequestsChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ShowPlaylistInNowPlaying")
                        .HasColumnType("boolean");

                    b.Property<decimal>("StationAdminRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("StationDjRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AzuraCastId");

                    b.ToTable("AzuraCastStations");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastStationMountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("AzuraCastStationMounts");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.GuildsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdminNotifyChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("AdminRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("ConfigSet")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ErrorChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UniqueId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastChecksEntity", b =>
                {
                    b.HasOne("AzzyBot.Data.Entities.AzuraCastEntity", "AzuraCast")
                        .WithOne("Checks")
                        .HasForeignKey("AzzyBot.Data.Entities.AzuraCastChecksEntity", "AzuraCastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AzuraCast");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastEntity", b =>
                {
                    b.HasOne("AzzyBot.Data.Entities.GuildsEntity", "Guild")
                        .WithOne("AzuraCast")
                        .HasForeignKey("AzzyBot.Data.Entities.AzuraCastEntity", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastStationChecksEntity", b =>
                {
                    b.HasOne("AzzyBot.Data.Entities.AzuraCastStationEntity", "Station")
                        .WithOne("Checks")
                        .HasForeignKey("AzzyBot.Data.Entities.AzuraCastStationChecksEntity", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastStationEntity", b =>
                {
                    b.HasOne("AzzyBot.Data.Entities.AzuraCastEntity", "AzuraCast")
                        .WithMany("Stations")
                        .HasForeignKey("AzuraCastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AzuraCast");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastStationMountEntity", b =>
                {
                    b.HasOne("AzzyBot.Data.Entities.AzuraCastStationEntity", "Station")
                        .WithMany("Mounts")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastEntity", b =>
                {
                    b.Navigation("Checks")
                        .IsRequired();

                    b.Navigation("Stations");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.AzuraCastStationEntity", b =>
                {
                    b.Navigation("Checks")
                        .IsRequired();

                    b.Navigation("Mounts");
                });

            modelBuilder.Entity("AzzyBot.Data.Entities.GuildsEntity", b =>
                {
                    b.Navigation("AzuraCast");
                });
#pragma warning restore 612, 618
        }
    }
}
