//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzzyBot.Bot.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzzyBot.Bot.Localization.CommandNames", typeof(CommandNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change-bot-status.
        /// </summary>
        internal static string change_bot_status {
            get {
                return ResourceManager.GetString("change-bot-status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get-joined-server.
        /// </summary>
        internal static string get_joined_server {
            get {
                return ResourceManager.GetString("get-joined-server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove-joined-server.
        /// </summary>
        internal static string remove_joined_server {
            get {
                return ResourceManager.GetString("remove-joined-server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send-bot-wide-message.
        /// </summary>
        internal static string send_bot_wide_message {
            get {
                return ResourceManager.GetString("send-bot-wide-message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view-logs.
        /// </summary>
        internal static string view_logs {
            get {
                return ResourceManager.GetString("view-logs", resourceCulture);
            }
        }
    }
}
