//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzzyBot.Bot.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandChoices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandChoices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzzyBot.Bot.Localization.CommandChoices", typeof(CommandChoices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3U.
        /// </summary>
        internal static string AzuraExportPlaylistProvider_m3u {
            get {
                return ResourceManager.GetString("AzuraExportPlaylistProvider.m3u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLS.
        /// </summary>
        internal static string AzuraExportPlaylistProvider_pls {
            get {
                return ResourceManager.GetString("AzuraExportPlaylistProvider.pls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string BooleanEnableDisableStateProvider_Disable {
            get {
                return ResourceManager.GetString("BooleanEnableDisableStateProvider.Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string BooleanEnableDisableStateProvider_Enable {
            get {
                return ResourceManager.GetString("BooleanEnableDisableStateProvider.Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string BooleanYesNoStateProvider_No {
            get {
                return ResourceManager.GetString("BooleanYesNoStateProvider.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string BooleanYesNoStateProvider_Yes {
            get {
                return ResourceManager.GetString("BooleanYesNoStateProvider.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competing.
        /// </summary>
        internal static string BotActivityProvider_Competing {
            get {
                return ResourceManager.GetString("BotActivityProvider.Competing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening To.
        /// </summary>
        internal static string BotActivityProvider_Listening {
            get {
                return ResourceManager.GetString("BotActivityProvider.Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        internal static string BotActivityProvider_Playing {
            get {
                return ResourceManager.GetString("BotActivityProvider.Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming.
        /// </summary>
        internal static string BotActivityProvider_Streaming {
            get {
                return ResourceManager.GetString("BotActivityProvider.Streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching.
        /// </summary>
        internal static string BotActivityProvider_Watching {
            get {
                return ResourceManager.GetString("BotActivityProvider.Watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Disturb.
        /// </summary>
        internal static string BotStatusProvider_Dnd {
            get {
                return ResourceManager.GetString("BotStatusProvider.Dnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        internal static string BotStatusProvider_Idle {
            get {
                return ResourceManager.GetString("BotStatusProvider.Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string BotStatusProvider_Offline {
            get {
                return ResourceManager.GetString("BotStatusProvider.Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string BotStatusProvider_Online {
            get {
                return ResourceManager.GetString("BotStatusProvider.Online", resourceCulture);
            }
        }
    }
}
