include:
  - ./AzzyBot/Modules/MusicStreaming/Files/docker-compose.yml
services:
  AzzyBot:
    container_name: AzzyBot
    image: sellagh/azzybot:latest
    restart: unless-stopped
    depends_on:
      - lavalink
    networks:
      - lavalink
    volumes:
      - ./AzzyBot/Settings:/app/Settings
      - ./AzzyBot/Customization:/app/Customization
