## Remove the comments from the lines if you want to use the Music Streaming module
## Do not forget to activate the Music Streaming module in the appsettings.json file then

#include:
#  - ./AzzyBot/Modules/MusicStreaming/Files/docker-compose.yml
services:
  AzzyBot:
    container_name: AzzyBot
    image: sellagh/azzybot:latest
    pull_policy: always
    restart: unless-stopped
    user: ${CURRENT_UID}
#    depends_on:
#      - lavalink
#    networks:
#      - lavalink
    volumes:
      - ./AzzyBot/Customization:/app/Customization
      - ./AzzyBot/Modules/AzuraCast/Files:/app/Modules/AzuraCast/Files
      - ./AzzyBot/Settings:/app/Settings
