name : Bug report
description : Create a bug report to help us fixing pesky bugs
title : "[BUG]"
labels : bug
assignees : Sella-GH
body :
  - type : markdown
    attributes :
      value: |
        Thank you very much for reporting an issue regarding Azzy.
        Please note that this form is only intended to be used for bug reports.
        If you want to suggest a feature, please use the [following form](https://github.com/Sella-GH/AzzyBot/issues/new?assignees=Sella-GH&labels=enhancement&projects=&template=feature_request.yml&title=%5BFEATURE%5D).

  - type : input
    id : bug-description
    attributes :
     label : "Describe the bug"
     description : "A clear and concise description of what the bug is."
    validations :
     required : true

  - type : textarea
    id : bug-reproducing
    attributes :
     label : "To reproduce"
     description : "Steps to reproduce the behavior."
     placeholder : |
      1. Go to "..."
      2. Click on "..."
      3. Scroll down to "..."
      4. See error
    validations :
      required : true

  - type : input
    id : expected-behavior
    attributes :
     label : "Expected behavior"
     description : "A clear and concise description of what you expected to happen."
    validations :
     required : true

  - type : textarea
    id : screenshots
    attributes :
     label : "Screenshots"
     description : "If applicable, add screenshots to help explain your issue."

  - type : textarea
    id : logs
    attributes :
     label : "Relevant log output"
     description : "If applicable, add relevant log output to help explain your issue."
     render : shell

  - type : dropdown
    id : operating-system
    attributes :
      label : "Operating system"
      description : "Which operating system are you using?"
      options :
        - Linux
        - MacOS
        - Windows
    validations :
      required : true

  - type : dropdown
    id : operating-system-arch
    attributes :
      label : "Architecture"
      description : "Which architecture are you using?"
      options :
        - ARM64
        - x64
    validations :
      required : true
      
  - type : textarea
    id : more-info
    attributes :
     label : "Additional information"
     description : "Add additional information if you want to provide some."
