name : Bug report
description : Create a bug report to help us fixing pesky bugs
title : "[BUG]"
labels : [bug]
assignees : Sella-GH
body :
  - type : markdown
    attributes :
      value: |
        Thank you very much for reporting an issue regarding Azzy.
        Please note that this form is only intended to be used for bug reports.
        If you want to suggest a feature, please use the [following form](https://github.com/Sella-GH/AzzyBot/issues/new?assignees=Sella-GH&labels=enhancement&projects=&template=feature_request.yml&title=%5BFEATURE%5D).

  - type : dropdown
    id : version
    attributes :
      label : "Version"
      description : "Which version of Azzy are you using?"
      options :
        - "1.9.x"
        - "1.10.x"
        - "2.0.0-preview1"
        - "2.0.0-preview1.1"
        - "2.0.0-preview2"
        - "2.0.0-preview3"
        - "2.0.0-preview3.1"
        - "2.0.0-preview4"
        - "2.0.0-preview4.1"
        - "2.0.0-preview5"
        - "2.0.0-preview6"
        - "2.0.0-preview7"
        - "2.0.0-preview8"
        - "2.0.0-preview9"
    validations :
      required : true

  - type : dropdown
    id : deploy-version
    attributes :
      label : "Deployment Version"
      description : "Which deployment version are you using?"
      options :
        - Docker
        - Native
    validations :
      required : true

  - type : dropdown
    id : operating-system
    attributes :
      label : "Operating System"
      description : "Which operating system are you using?"
      options :
        - Linux
        - MacOS
        - Windows
    validations :
      required : true

  - type: input
    id: operating-system-version
    attributes:
      label: "Operating System Version"
      description: "Which version of the operating system are you using?"
      placeholder: "e.g. Windows 11 Pro 23H2 Build 22635.3790 (use winver) // Debian 12.5 // MacOS 14.5"
    validations:
      required: true

  - type : dropdown
    id : operating-system-arch
    attributes :
      label : "Architecture"
      description : "Which architecture are you using?"
      options :
        - ARM64
        - x64
    validations :
      required : true

  - type : input
    id : bug-description
    attributes :
      label : "Describe The Bug"
      description : "A clear and concise description of what the bug is.\nPlease make sure to provide as much information as possible."
      placeholder : "The bot crashes when [...]"
    validations :
      required : true

  - type : textarea
    id : bug-reproducing
    attributes :
      label : "Reproduction Steps"
      description : "Steps to reproduce the behavior.\nIf applicable, add screenshots to help explain your issue"
      placeholder : |
        1. Go to "..."
        2. Click on "..."
        3. Scroll down to "..."
        4. See error
    validations :
      required : true

  - type : textarea
    id : expected-behavior
    attributes :
      label : "Expected Behavior"
      description : "A clear and concise description of what you expected to happen.\nPlease make sure to provide as much information as possible."
      placeholder : "I expected the bot to [...]"
    validations :
      required : true

  - type : textarea
    id : logs
    attributes :
      label : "Relevant Log Output"
      description : "If applicable, add relevant log output of the logging file to help explain your issue.\nPlease make sure to remove any sensitive information."
      render : shell

  - type : textarea
    id : more-info
    attributes :
      label : "Additional information"
      description : "Add additional information if you want to provide some."
      placeholder : "I've also noticed that [...]"
