name : Bug report
description : Create a bug report to help us fixing pesky bugs
title : "[BUG]"
labels : [bug]
assignees : Sella-GH
body :
  - type : markdown
    attributes :
      value: |
        Thank you very much for reporting an issue regarding Azzy.
        Please note that this form is only intended to be used for bug reports.
        If you want to suggest a feature, please use the [following form](https://github.com/Sella-GH/AzzyBot/issues/new?assignees=Sella-GH&labels=enhancement&projects=&template=feature_request.yml&title=%5BFEATURE%5D).

  - type : dropdown
    id : azzy_version
    attributes :
      label : "Azzy Bot Version"
      description : "Which version of Azzy are you using? Ensure you're using the latest minor version of your line!"
      options :
        - "2.8.x"
        - "2.7.x"
        - "2.6.x"
        - "2.5.x"
        - "2.4.x"
        - "2.3.x"
        - "2.2.x"
        - "2.1.x"
        - "2.0.x"
        - "1.10.x"
        - "1.9.x"
    validations :
      required : true

  - type : dropdown
    id : operating_system_arch
    attributes :
      label : "Architecture"
      description : "Which architecture are you using?"
      options :
        - ARM64
        - x64
    validations :
      required : true

  - type : dropdown
    id: azura_channel
    attributes:
      label: "AzuraCast Release Channel"
      description : "Which release channel of AzuraCast are you using?"
      options :
        - Rolling Release Channel
        - Stable Channel
    validations:
      required: true

  - type : input
    id : azura_version
    attributes :
      label : "AzuraCast Version"
      description : "Which version of AzuraCast are you currently running? You can find this in the footer of most pages."
      placeholder : "0.12.3 or Rolling Release #abcdefg (2020-01-01)"

  - type : dropdown
    id : deploy_version
    attributes :
      label : "Deployment Version"
      description : "Which deployment version are you using?"
      options :
        - Docker
        #- Native
    validations :
      required : true

  - type : dropdown
    id : operating_system
    attributes :
      label : "Operating System"
      description : "Which operating system are you using?"
      options :
        - Linux
        - MacOS
        - Windows
    validations :
      required : true

  - type: input
    id: operating_system_version
    attributes:
      label: "Operating System Version"
      description: "Which version of the operating system are you using?"
      placeholder: "e.g. Windows 11 Pro 23H2 Build 22635.3790 (use winver) // Debian 12.5 // MacOS 14.5"
    validations:
      required: true

  - type : input
    id : bug_description
    attributes :
      label : "Describe The Bug"
      description : "A clear and concise description of what the bug is.\nPlease make sure to provide as much information as possible."
      placeholder : "The bot crashes when [...]"
    validations :
      required : true

  - type : textarea
    id : bug_reproducing
    attributes :
      label : "Reproduction Steps"
      description : "Steps to reproduce the behavior.\nIf applicable, add screenshots to help explain your issue"
      placeholder : |
        1. Go to "..."
        2. Click on "..."
        3. Scroll down to "..."
        4. See error
    validations :
      required : true

  - type : textarea
    id : expected_behavior
    attributes :
      label : "Expected Behavior"
      description : "A clear and concise description of what you expected to happen.\nPlease make sure to provide as much information as possible."
      placeholder : "I expected the bot to [...]"
    validations :
      required : true

  - type : textarea
    id : logs
    attributes :
      label : "Relevant Log Output"
      description : "If applicable, add relevant log output of the logging file to help explain your issue.\nPlease make sure to remove any sensitive information."
      render : shell

  - type : textarea
    id : more_info
    attributes :
      label : "Additional information"
      description : "Add additional information if you want to provide some."
      placeholder : "I've also noticed that [...]"
