name : Feature requests
description : Create a feature request to help us improving the discord bot.
title : "[FEATURE]"
labels : [enhancement]
assignees : Sella-GH
body :
  - type : markdown
    attributes :
      value: |
        Thank you very much for suggesting a feature for Azzy.
        Please note that this form is only intended to be used for feature requests.
        If you want to report a bug, please use the [following form](https://github.com/Sella-GH/AzzyBot/issues/new?assignees=Sella-GH&labels=bug&projects=&template=bug_report.yml&title=%5BBUG%5D).

  - type : textarea
    id : feature-description
    attributes :
     label : "Explain Your Issue"
     description : "A clear and concise description of what the issue is. You are able to link existing GitHub issues with a #."
     placeholder : "I'm always frustrated when [...]"
    validations :
     required : true

  - type : textarea
    id : expected-behavior
    attributes :
     label : "Describe Your Solution"
     description : "A clear and concise description of what you want us to implement and what should happen."
     placeholder : "I would like to see [...]"
    validations :
     required : true

  - type : textarea
    id : alternatives
    attributes :
     label : "Describe Alternative Solutions"
     description : "A clear and concise description of any alternative solution or feature you've considered."
     placeholder : "I've considered [...]"
    validations :
     required : true
     
  - type : textarea
    id : more-info
    attributes :
     label : "Additional Information"
     description : "Add additional information if you want to provide some."
     placeholder : "I've also noticed that [...]"
