//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzzyBot.Bot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UriStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UriStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzzyBot.Bot.Resources.UriStrings", typeof(UriStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/AzuraCast/AzuraCast/main/resources/icon.png.
        /// </summary>
        internal static string AzuraCastPic {
            get {
                return ResourceManager.GetString("AzuraCastPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AzuraCast/AzuraCast/commits/main.
        /// </summary>
        internal static string AzuraCastRollingUrl {
            get {
                return ResourceManager.GetString("AzuraCastRollingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AzuraCast/AzuraCast/blob/stable/CHANGELOG.md.
        /// </summary>
        internal static string AzuraCastStableUrl {
            get {
                return ResourceManager.GetString("AzuraCastStableUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Sella-GH/AzzyBot/issues/new?assignees=Sella-GH&amp;labels=bug&amp;projects=&amp;template=bug_report.yml&amp;title=%5BBUG%5D.
        /// </summary>
        internal static string BugReportUri {
            get {
                return ResourceManager.GetString("BugReportUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.ipify.org.
        /// </summary>
        internal static string GetIpv4Uri {
            get {
                return ResourceManager.GetString("GetIpv4Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api6.ipify.org.
        /// </summary>
        internal static string GetIpv6Uri {
            get {
                return ResourceManager.GetString("GetIpv6Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Sella-GH.
        /// </summary>
        internal static string GitHubCreatorUri {
            get {
                return ResourceManager.GetString("GitHubCreatorUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Sella-GH/AzzyBot/commit.
        /// </summary>
        internal static string GitHubRepoCommitUri {
            get {
                return ResourceManager.GetString("GitHubRepoCommitUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Sella-GH/AzzyBot/graphs/contributors.
        /// </summary>
        internal static string GitHubRepoContribUri {
            get {
                return ResourceManager.GetString("GitHubRepoContribUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Sella-GH/AzzyBot.
        /// </summary>
        internal static string GitHubRepoUri {
            get {
                return ResourceManager.GetString("GitHubRepoUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com.
        /// </summary>
        internal static string GitHubUri {
            get {
                return ResourceManager.GetString("GitHubUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Sella-GH/AzzyBot/wiki/Setup-instructions.
        /// </summary>
        internal static string SetupInstructions {
            get {
                return ResourceManager.GetString("SetupInstructions", resourceCulture);
            }
        }
    }
}
