// <auto-generated />
using System;
using AzzyBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzzyBot.Migrations
{
    [DbContext(typeof(AzzyDbContext))]
    [Migration("20240526173639_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastChecksEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("FileChanges")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ServerStatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<bool>("Updates")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UpdatesShowChangelog")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("StationId")
                        .IsUnique();

                    b.ToTable("AzuraCastChecks");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GuildId")
                        .HasColumnType("int");

                    b.Property<ulong>("OutagesChannelId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("AzuraCast");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastMountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mount")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("AzuraCastMounts");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastStationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AzuraCastId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PreferHls")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("RequestsChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("ShowPlaylistInNowPlaying")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AzuraCastId");

                    b.ToTable("AzuraCastStations");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.GuildsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AzuraCastSet")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ConfigSet")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("ErrorChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsDebugAllowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("UniqueId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastChecksEntity", b =>
                {
                    b.HasOne("AzzyBot.Database.Entities.AzuraCastStationEntity", "Station")
                        .WithOne("Checks")
                        .HasForeignKey("AzzyBot.Database.Entities.AzuraCastChecksEntity", "StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastEntity", b =>
                {
                    b.HasOne("AzzyBot.Database.Entities.GuildsEntity", "Guild")
                        .WithOne("AzuraCast")
                        .HasForeignKey("AzzyBot.Database.Entities.AzuraCastEntity", "GuildId");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastMountEntity", b =>
                {
                    b.HasOne("AzzyBot.Database.Entities.AzuraCastStationEntity", "Station")
                        .WithMany("Mounts")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastStationEntity", b =>
                {
                    b.HasOne("AzzyBot.Database.Entities.AzuraCastEntity", "AzuraCast")
                        .WithMany("Stations")
                        .HasForeignKey("AzuraCastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AzuraCast");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastEntity", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.AzuraCastStationEntity", b =>
                {
                    b.Navigation("Checks")
                        .IsRequired();

                    b.Navigation("Mounts");
                });

            modelBuilder.Entity("AzzyBot.Database.Entities.GuildsEntity", b =>
                {
                    b.Navigation("AzuraCast");
                });
#pragma warning restore 612, 618
        }
    }
}
