using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json.Serialization;
using AzzyBot.Bot.Settings;
using AzzyBot.Bot.Utilities.Records;
using AzzyBot.Bot.Utilities.Records.AzuraCast;
using AzzyBot.Core.Utilities.Records;

namespace AzzyBot.Bot.Utilities;

[SuppressMessage("Roslynator", "RCS1251:Remove unnecessary braces from record declaration", Justification = "Class has to be empty.")]
[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(AppStatsRecord))]
[JsonSerializable(typeof(AzuraAdminStationConfigRecord))]
[JsonSerializable(typeof(AzuraAdminStationConfigBackendRecord))]
[JsonSerializable(typeof(AzuraCustomQueueItemRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraFilesRecord>))]
[JsonSerializable(typeof(AzuraFilesDetailedRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraFilesDetailedRecord>))]
[JsonSerializable(typeof(AzuraFilesPlaylistRecord))]
[JsonSerializable(typeof(AzuraFileComplianceRecord))]
[JsonSerializable(typeof(AzuraHardwareStatsRecord))]
[JsonSerializable(typeof(AzuraCpuData))]
[JsonSerializable(typeof(AzuraCpuTotalData))]
[JsonSerializable(typeof(AzuraCoreData))]
[JsonSerializable(typeof(AzuraMemoryData))]
[JsonSerializable(typeof(AzuraDiskData))]
[JsonSerializable(typeof(AzuraReadableDiskData))]
[JsonSerializable(typeof(AzuraReadableMemoryData))]
[JsonSerializable(typeof(AzuraNetworkData))]
[JsonSerializable(typeof(AzuraSpeedData))]
[JsonSerializable(typeof(AzuraTransmissionData))]
[JsonSerializable(typeof(AzuraStationMountRecord))]
[JsonSerializable(typeof(AzuraHlsMountRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraHlsMountRecord>))]
[JsonSerializable(typeof(AzuraMountRecord))]
[JsonSerializable(typeof(AzuraMountLinksRecord))]
[JsonSerializable(typeof(AzuraMountLinksBaseRecord))]
[JsonSerializable(typeof(AzuraDefaultMountBaseRecord))]
[JsonSerializable(typeof(AzuraMountBaseRecord))]
[JsonSerializable(typeof(AzuraNowPlayingDataRecord))]
[JsonSerializable(typeof(AzuraNowPlayingListenersRecord))]
[JsonSerializable(typeof(AzuraNowPlayingLiveRecord))]
[JsonSerializable(typeof(AzuraNowPlayingRecord))]
[JsonSerializable(typeof(AzuraPlaylistRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraPlaylistRecord>))]
[JsonSerializable(typeof(AzuraPlaylistLinkRecord))]
[JsonSerializable(typeof(AzuraPlaylistLinkExportRecord))]
[JsonSerializable(typeof(AzuraPlaylistStateRecord))]
[JsonSerializable(typeof(AzuraRequestRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraRequestRecord>))]
[JsonSerializable(typeof(AzuraRequestQueueItemRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraRequestQueueItemRecord>))]
[JsonSerializable(typeof(AzuraSongDataRecord))]
[JsonSerializable(typeof(AzuraSongAdvancedDataRecord))]
[JsonSerializable(typeof(AzuraSongBasicDataRecord))]
[JsonSerializable(typeof(AzuraMediaItemRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraMediaItemRecord>))]
[JsonSerializable(typeof(AzuraTrackRecord))]
[JsonSerializable(typeof(AzuraStationHistoryItemRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraStationHistoryItemRecord>))]
[JsonSerializable(typeof(AzuraStationHistoryExportRecord))]
[JsonSerializable(typeof(AzuraStationListenerRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraStationListenerRecord>))]
[JsonSerializable(typeof(AzuraStationQueueItemRecord))]
[JsonSerializable(typeof(AzuraStationQueueItemDetailedRecord))]
[JsonSerializable(typeof(IEnumerable<AzuraStationQueueItemDetailedRecord>))]
[JsonSerializable(typeof(AzuraStationRecord))]
[JsonSerializable(typeof(AzuraStationStatusRecord))]
[JsonSerializable(typeof(AzuraStatusRecord))]
[JsonSerializable(typeof(AzuraSystemLogsRecord))]
[JsonSerializable(typeof(AzuraSystemLogEntryRecord))]
[JsonSerializable(typeof(AzuraSystemLogRecord))]
[JsonSerializable(typeof(AzuraUpdateRecord))]
[JsonSerializable(typeof(AzuraUpdateErrorRecord))]
[JsonSerializable(typeof(AzzyBotSettingsRecord))]
[JsonSerializable(typeof(List<AzzyUpdateRecord>))]
public sealed partial class JsonDeserializationSourceGen : JsonSerializerContext
{
}
