name: Update DSharpPlus Nightly version

on:
  push:
    path:
      - "**update-dsp.yml"
  schedule:
    - cron: "00 12 * * 0"
    - cron: "00 16 * * 1-5"
    - cron: "00 12 * * 6"

jobs:
  CheckForUpdates:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version from project
      id: extracted_version
      run: |
        VERSION=$(grep -Po '(?<=<PackageReference Include="DSharpPlus" Version=")[^"]*' AzzyBot-Next/AzzyBot-Next.csproj)
        echo "Current version is $VERSION"