name: Update DSharpPlus Nightly version

on:
  push:
    paths:
      - "**update-dsp.yml"
  schedule:
    - cron: '0 */6 * * *'

jobs:
  CheckForUpdates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev-next

      - name: Extract current NuGet package version
        id: current_version
        run: |
          VERSION=$(grep -Po '(?<=<PackageReference Include="DSharpPlus" Version=")[^"]*' AzzyBot-Next/AzzyBot-Next.csproj)
          echo "Current package version is $VERSION"
          echo "CURRENT_VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Fetch the latest package version from NuGet
        id: nuget_version
        run: |
          # Fetch data from NuGet API and save to a JSON file
          curl -s "https://api.nuget.org/v3-flatcontainer/dsharpplus/index.json" -o nuget_data.json
          # Check if the JSON file contains any versions
          if jq .versions nuget_data.json | jq -e 'length > 0' > /dev/null; then
            # Extract the latest version
            LATEST_VERSION=$(jq -r '.versions[-2]' nuget_data.json)
            echo "Latest NuGet package version is $LATEST_VERSION"
            echo "NUGET_VERSION=$LATEST_VERSION" >> "$GITHUB_OUTPUT"
          else
            echo "No versions found in the NuGet package data."
          fi

      - name: Update .csproj file if versions differ
        if: ${{ steps.current_version.outputs.CURRENT_VERSION != steps.nuget_version.outputs.NUGET_VERSION }}
        run: |
          sed -i 's/<PackageReference Include="DSharpPlus" Version="'${{ steps.current_version.outputs.CURRENT_VERSION }}'"/<PackageReference Include="DSharpPlus" Version="'${{ steps.nuget_version.outputs.NUGET_VERSION }}'"/' AzzyBot-Next/AzzyBot-Next.csproj
          sed -i 's/<PackageReference Include="DSharpPlus.Commands" Version="'${{ steps.current_version.outputs.CURRENT_VERSION }}'"/<PackageReference Include="DSharpPlus.Commands" Version="'${{ steps.nuget_version.outputs.NUGET_VERSION }}'"/' AzzyBot-Next/AzzyBot-Next.csproj

      - name: Commit and push if there was a change
        if: ${{ steps.current_version.outputs.CURRENT_VERSION != steps.nuget_version.outputs.NUGET_VERSION }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add AzzyBot-Next/AzzyBot-Next.csproj
          git commit -m "Update DSharpPlus Nightly to ${{ steps.nuget_version.outputs.NUGET_VERSION }}"
          git push
